"""
Alara Learning Feed models.

Design notes:
- All business-critical counters are denormalized onto FeedLesson and kept
  consistent by PostgreSQL triggers (see sql/supabase_feed_schema.sql).
- The `search_vector` field is generated by PostgreSQL and is read-only in
  Django (editable=False). Do not write to it from Python.
- Learning profiles are independent of official academic records.
"""
from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import SearchVectorField
from django.db import models
from django.conf import settings


User = settings.AUTH_USER_MODEL


# ---------------------------------------------------------------------------
# Reference tables
# ---------------------------------------------------------------------------

class FeedAcademicLevel(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    order = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'feed_feedacademiclevel'
        ordering = ['order', 'name']

    def __str__(self):
        return self.name


class FeedAcademicClass(models.Model):
    level = models.ForeignKey(FeedAcademicLevel, on_delete=models.RESTRICT, related_name='classes')
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    order = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'feed_feedacademicclass'
        unique_together = ['level', 'slug']
        ordering = ['order', 'name']

    def __str__(self):
        return self.name


class FeedSubject(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'feed_feedsubject'
        ordering = ['name']

    def __str__(self):
        return self.name


class FeedTag(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    usage_count = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'feed_feedtag'
        ordering = ['-usage_count', 'name']

    def __str__(self):
        return self.name


# ---------------------------------------------------------------------------
# Learning profile
# ---------------------------------------------------------------------------

class LearningProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='learning_profile')
    preferred_level = models.ForeignKey(
        FeedAcademicLevel, on_delete=models.SET_NULL, null=True, blank=True,
        related_name='learning_profiles'
    )
    preferred_class = models.ForeignKey(
        FeedAcademicClass, on_delete=models.SET_NULL, null=True, blank=True,
        related_name='learning_profiles'
    )
    preferred_subjects = models.ManyToManyField(
        FeedSubject, blank=True, related_name='learning_profiles'
    )
    preferred_subject_ids = models.JSONField(default=list, blank=True)
    preferences = models.JSONField(default=dict, blank=True)
    learning_streak_days = models.IntegerField(default=0)
    last_learning_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'feed_learningprofile'

    def __str__(self):
        return f"LearningProfile({self.user_id})"


# ---------------------------------------------------------------------------
# Lessons & resources
# ---------------------------------------------------------------------------

class FeedLesson(models.Model):
    VISIBILITY_CHOICES = (
        ('draft', 'Draft'),
        ('pending_review', 'Pending Review'),
        ('public', 'Public'),
        ('school_only', 'School Only'),
        ('hidden', 'Hidden'),
        ('suspended', 'Suspended'),
    )
    STATUS_CHOICES = (
        ('pending_review', 'Pending Review'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected'),
        ('suspended', 'Suspended'),
    )
    VERIFICATION_CHOICES = (
        ('pending', 'Pending'),
        ('verified', 'Verified'),
        ('rejected', 'Rejected'),
    )

    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    topic = models.CharField(max_length=255, blank=True)

    teacher = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='feed_lessons',
        limit_choices_to={'role': 'teacher'}
    )
    school = models.ForeignKey(
        'schools.School', on_delete=models.SET_NULL, null=True, blank=True,
        related_name='feed_lessons'
    )

    level = models.ForeignKey(
        FeedAcademicLevel, on_delete=models.SET_NULL, null=True, blank=True,
        related_name='lessons'
    )
    class_obj = models.ForeignKey(
        FeedAcademicClass, on_delete=models.SET_NULL, null=True, blank=True,
        related_name='lessons'
    )
    subject = models.ForeignKey(
        FeedSubject, on_delete=models.SET_NULL, null=True, blank=True,
        related_name='lessons'
    )
    tags = models.ManyToManyField(FeedTag, blank=True, related_name='lessons')

    visibility = models.CharField(max_length=20, choices=VISIBILITY_CHOICES, default='public')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending_review')
    verification_status = models.CharField(max_length=20, choices=VERIFICATION_CHOICES, default='pending')

    duration_seconds = models.IntegerField(default=0)
    thumbnail_url = models.URLField(max_length=1000, blank=True)
    poster_url = models.URLField(max_length=1000, blank=True)
    extra_metadata = models.JSONField(default=dict, blank=True)

    # ── Cloudflare Stream fields ─────────────────────────────────
    # Replaces the old Supabase video_url / LessonResource-based video.
    # When a video is uploaded to Cloudflare Stream, these fields are populated.
    cloudflare_video_uid = models.CharField(max_length=255, blank=True, db_index=True)
    cloudflare_playback_url = models.URLField(max_length=1000, blank=True)
    cloudflare_thumbnail_url = models.URLField(max_length=1000, blank=True)
    video_duration = models.FloatField(default=0.0)

    # Denormalized counters (maintained by DB triggers)
    view_count = models.BigIntegerField(default=0)
    unique_view_count = models.BigIntegerField(default=0)
    like_count = models.BigIntegerField(default=0)
    save_count = models.BigIntegerField(default=0)
    comment_count = models.BigIntegerField(default=0)
    share_count = models.BigIntegerField(default=0)
    download_count = models.BigIntegerField(default=0)
    completion_rate = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    avg_watch_seconds = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    trending_score = models.DecimalField(max_digits=12, decimal_places=6, default=0.000000)
    quality_score = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)

    published_at = models.DateTimeField(null=True, blank=True)

    # Read-only generated column maintained by PostgreSQL trigger
    search_vector = SearchVectorField(null=True, editable=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'feed_feedlesson'
        ordering = ['-published_at', '-created_at']
        indexes = [
            models.Index(fields=['teacher']),
            models.Index(fields=['school']),
            models.Index(fields=['level']),
            models.Index(fields=['class_obj']),
            models.Index(fields=['subject']),
            models.Index(fields=['visibility', 'status']),
            models.Index(fields=['visibility', 'status', '-published_at']),
            models.Index(fields=['-trending_score', '-published_at']),
            models.Index(fields=['-published_at']),
            models.Index(fields=['-completion_rate']),
            models.Index(fields=['school', 'status', 'visibility']),
            models.Index(fields=['level', 'class_obj', 'subject', 'status', 'visibility']),
            GinIndex(fields=['search_vector']),
            GinIndex(fields=['title'], name='feedlesson_title_gin', opclasses=['gin_trgm_ops']),
            GinIndex(fields=['topic'], name='feedlesson_topic_gin', opclasses=['gin_trgm_ops']),
        ]

    def __str__(self):
        return self.title


class LessonResource(models.Model):
    RESOURCE_TYPES = (
        ('video', 'Video'),
        ('pdf', 'PDF'),
        ('image', 'Image'),
        ('audio', 'Audio'),
        ('assignment', 'Assignment'),
        ('quiz', 'Quiz'),
    )

    lesson = models.ForeignKey(FeedLesson, on_delete=models.CASCADE, related_name='resources')
    resource_type = models.CharField(max_length=20, choices=RESOURCE_TYPES)
    title = models.CharField(max_length=255, blank=True)
    storage_bucket = models.CharField(max_length=100)
    storage_path = models.TextField()
    public_url = models.URLField(max_length=1000, blank=True)
    file_size = models.BigIntegerField(null=True, blank=True)
    mime_type = models.CharField(max_length=100, blank=True)
    duration_seconds = models.IntegerField(null=True, blank=True)
    width = models.IntegerField(null=True, blank=True)
    height = models.IntegerField(null=True, blank=True)
    page_count = models.IntegerField(null=True, blank=True)
    extra_metadata = models.JSONField(default=dict, blank=True)
    sort_order = models.IntegerField(default=0)
    is_primary = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'feed_lessonresource'
        ordering = ['sort_order', 'id']

    def __str__(self):
        return f"{self.resource_type}:{self.storage_path}"


# ---------------------------------------------------------------------------
# Engagement
# ---------------------------------------------------------------------------

class FeedLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='feed_likes')
    lesson = models.ForeignKey(FeedLesson, on_delete=models.CASCADE, related_name='likes')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'feed_feedlike'
        unique_together = ['user', 'lesson']
        ordering = ['-created_at']

    def __str__(self):
        return f"Like({self.user_id}, {self.lesson_id})"


class FeedSave(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='feed_saves')
    lesson = models.ForeignKey(FeedLesson, on_delete=models.CASCADE, related_name='saves')
    offline_download_metadata = models.JSONField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'feed_feedsave'
        unique_together = ['user', 'lesson']
        ordering = ['-created_at']

    def __str__(self):
        return f"Save({self.user_id}, {self.lesson_id})"


class WatchHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='feed_watch_history')
    lesson = models.ForeignKey(FeedLesson, on_delete=models.CASCADE, related_name='watch_history')
    watch_seconds = models.IntegerField(default=0)
    completion_percentage = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    is_completed = models.BooleanField(default=False)
    resume_position_seconds = models.IntegerField(default=0)
    last_watched_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'feed_watchhistory'
        unique_together = ['user', 'lesson']
        ordering = ['-last_watched_at']

    def __str__(self):
        return f"WatchHistory({self.user_id}, {self.lesson_id})"


class TeacherFollower(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following_teachers')
    teacher = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='teacher_followers',
        limit_choices_to={'role': 'teacher'}
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'feed_teacherfollower'
        unique_together = ['user', 'teacher']
        ordering = ['-created_at']

    def __str__(self):
        return f"Follow({self.user_id} -> {self.teacher_id})"


# ---------------------------------------------------------------------------
# Comments
# ---------------------------------------------------------------------------

class FeedComment(models.Model):
    lesson = models.ForeignKey(FeedLesson, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='feed_comments')
    parent = models.ForeignKey(
        'self', on_delete=models.CASCADE, null=True, blank=True,
        related_name='replies'
    )
    body = models.TextField()
    is_pinned = models.BooleanField(default=False)
    is_moderated = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)
    like_count = models.BigIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'feed_feedcomment'
        ordering = ['-is_pinned', '-created_at']

    def __str__(self):
        return f"Comment({self.id})"


class CommentLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='feed_comment_likes')
    comment = models.ForeignKey(FeedComment, on_delete=models.CASCADE, related_name='likes')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'feed_commentlike'
        unique_together = ['user', 'comment']
        ordering = ['-created_at']

    def __str__(self):
        return f"CommentLike({self.user_id}, {self.comment_id})"


# ---------------------------------------------------------------------------
# Notifications
# ---------------------------------------------------------------------------

class FeedNotification(models.Model):
    NOTIFICATION_TYPES = (
        ('new_lesson', 'New Lesson'),
        ('teacher_reply', 'Teacher Reply'),
        ('comment_reply', 'Comment Reply'),
        ('follower', 'New Follower'),
        ('report_update', 'Report Update'),
        ('lesson_approved', 'Lesson Approved'),
        ('lesson_suspended', 'Lesson Suspended'),
        ('general', 'General'),
    )
    PRIORITY_CHOICES = (
        ('low', 'Low'),
        ('normal', 'Normal'),
        ('high', 'High'),
        ('urgent', 'Urgent'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='feed_notifications')
    notification_type = models.CharField(max_length=30, choices=NOTIFICATION_TYPES)
    title = models.CharField(max_length=255)
    message = models.TextField(blank=True)
    lesson = models.ForeignKey(
        FeedLesson, on_delete=models.SET_NULL, null=True, blank=True,
        related_name='notifications'
    )
    comment = models.ForeignKey(
        FeedComment, on_delete=models.SET_NULL, null=True, blank=True,
        related_name='notifications'
    )
    actor = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True,
        related_name='feed_notifications_sent'
    )
    related_object_type = models.CharField(max_length=50, blank=True)
    related_object_id = models.CharField(max_length=50, blank=True)
    is_read = models.BooleanField(default=False)
    priority = models.CharField(max_length=20, choices=PRIORITY_CHOICES, default='normal')
    created_at = models.DateTimeField(auto_now_add=True)
    read_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'feed_feednotification'
        ordering = ['-created_at']

    def __str__(self):
        return f"Notification({self.user_id}: {self.title})"


# ---------------------------------------------------------------------------
# Reports & moderation
# ---------------------------------------------------------------------------

class FeedReport(models.Model):
    TARGET_TYPES = (
        ('lesson', 'Lesson'),
        ('comment', 'Comment'),
        ('teacher', 'Teacher'),
    )
    STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('reviewing', 'Reviewing'),
        ('resolved', 'Resolved'),
        ('dismissed', 'Dismissed'),
    )

    reporter = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True,
        related_name='feed_reports_made'
    )
    target_type = models.CharField(max_length=20, choices=TARGET_TYPES)
    lesson = models.ForeignKey(
        FeedLesson, on_delete=models.CASCADE, null=True, blank=True,
        related_name='reports'
    )
    comment = models.ForeignKey(
        FeedComment, on_delete=models.CASCADE, null=True, blank=True,
        related_name='reports'
    )
    teacher = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True,
        related_name='feed_reports_received'
    )
    reason = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    resolution = models.TextField(blank=True)
    resolved_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True,
        related_name='feed_reports_resolved'
    )
    resolved_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'feed_feedreport'
        ordering = ['-created_at']

    def __str__(self):
        return f"Report({self.target_type}:{self.id})"


# ---------------------------------------------------------------------------
# Search & recommendations
# ---------------------------------------------------------------------------

class FeedSearchQuery(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True,
        related_name='feed_search_queries'
    )
    query = models.TextField()
    result_count = models.IntegerField(null=True, blank=True)
    ip_hash = models.CharField(max_length=64, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'feed_feedsearchquery'
        ordering = ['-created_at']

    def __str__(self):
        return self.query[:50]


class RecommendationCache(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True,
        related_name='recommendation_caches'
    )
    cache_key = models.CharField(max_length=255)
    strategy = models.CharField(max_length=50)
    lesson_ids = models.JSONField(default=list)
    metadata = models.JSONField(default=dict)
    expires_at = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'feed_recommendationcache'
        unique_together = ['user', 'cache_key']

    def __str__(self):
        return f"RecCache({self.user_id}:{self.cache_key})"


# ---------------------------------------------------------------------------
# Guest Learner
# ---------------------------------------------------------------------------

class GuestLearner(models.Model):
    """
    Stores a guest learner's profile keyed by a client-generated device UUID.

    When a user skips login, they provide:
      - device_id (UUID v4, generated client-side)
      - name
      - academic level, class, and subject interests

    Guest likes and feed activity can be tracked against this record.
    """
    device_id = models.UUIDField(
        primary_key=True,
        help_text="Client-generated UUID v4 stored in FlutterSecureStorage",
    )
    name = models.CharField(max_length=255)
    level = models.ForeignKey(
        'FeedAcademicLevel',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='guest_learners',
    )
    class_obj = models.ForeignKey(
        'FeedAcademicClass',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='guest_learners',
    )
    subjects = models.ManyToManyField(
        'FeedSubject',
        blank=True,
        related_name='guest_learners',
    )
    subject_ids = models.JSONField(default=list, blank=True)

    # Engagement
    liked_lesson_ids = models.JSONField(default=list, blank=True)
    onboarding_completed_at = models.DateTimeField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'feed_guestlearner'
        verbose_name = 'Guest Learner'
        verbose_name_plural = 'Guest Learners'

    def __str__(self):
        return f"Guest({self.device_id}: {self.name})"


# ---------------------------------------------------------------------------
# Analytics
# ---------------------------------------------------------------------------

class LessonAnalytics(models.Model):
    lesson = models.OneToOneField(
        FeedLesson, on_delete=models.CASCADE, related_name='analytics'
    )
    views = models.BigIntegerField(default=0)
    unique_views = models.BigIntegerField(default=0)
    total_watch_seconds = models.BigIntegerField(default=0)
    avg_watch_seconds = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    likes = models.BigIntegerField(default=0)
    saves = models.BigIntegerField(default=0)
    comments = models.BigIntegerField(default=0)
    shares = models.BigIntegerField(default=0)
    downloads = models.BigIntegerField(default=0)
    completions = models.BigIntegerField(default=0)
    completion_rate = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    date = models.JSONField(default=dict, blank=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'feed_lessonanalytics'

    def __str__(self):
        return f"Analytics({self.lesson_id})"


class DailyAnalytics(models.Model):
    date = models.DateField()
    school = models.ForeignKey(
        'schools.School', on_delete=models.SET_NULL, null=True, blank=True,
        related_name='feed_daily_analytics'
    )
    metric_name = models.CharField(max_length=50)
    metric_value = models.BigIntegerField(default=0)
    dimension = models.CharField(max_length=100, blank=True)

    class Meta:
        db_table = 'feed_dailyanalytics'
        unique_together = ['date', 'school', 'metric_name', 'dimension']
        indexes = [
            models.Index(fields=['date', 'metric_name']),
            models.Index(fields=['school', 'date']),
        ]

    def __str__(self):
        return f"DailyAnalytics({self.date}:{self.metric_name})"
