-- =============================================================================
-- ASSESSMENT TYPE SYSTEM — Grading Migration
-- =============================================================================
-- Adds school-admin-managed assessment types (Assignment, Class Exercise, Quiz,
-- Exam, ...) with per-session weight percentages, links assessments to a type,
-- and links student grades to the specific assessment they were graded on.
--
-- This migration mirrors the Python model changes:
--   1. academics_assessmenttype           (new table)
--   2. academics_assessment.assessment_type_id  (new FK column)
--   3. students_grade.assessment_id       (new FK column)
--   4. students_grade.assessment_type     (extended choices — no column change,
--                                          values are plain VARCHAR)
--
-- Run with:  psql "DATABASE_URL" -f backend/assessment_type_migration.sql
-- or:        psql -h <host> -U <user> -d <db> -f backend/assessment_type_migration.sql
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Create academics_assessmenttype
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "academics_assessmenttype" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(100) NOT NULL,
    "category" varchar(25) NOT NULL,
    "weight_percentage" double precision NOT NULL,
    "is_active" boolean NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "school_id" bigint NOT NULL,
    "academic_session_id" bigint NULL,
    CONSTRAINT "academics_assessmenttype_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "academics_assessmenttype_academic_session_id_fk" FOREIGN KEY ("academic_session_id") REFERENCES "academics_academicsession" ("id") DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "academics_assessmenttype_school_id_fk" FOREIGN KEY ("school_id") REFERENCES "schools_school" ("id") DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "academics_assessmenttype_school_academic_sessi_unique" UNIQUE ("school_id", "academic_session_id", "name")
);

CREATE INDEX IF NOT EXISTS "academics_assessmenttype_school_id_idx" ON "academics_assessmenttype" ("school_id");
CREATE INDEX IF NOT EXISTS "academics_assessmenttype_academic_session_id_idx" ON "academics_assessmenttype" ("academic_session_id");

-- -----------------------------------------------------------------------------
-- 2. Add assessment_type_id FK to academics_assessment
-- -----------------------------------------------------------------------------
ALTER TABLE "academics_assessment"
    ADD COLUMN IF NOT EXISTS "assessment_type_id" bigint NULL;

ALTER TABLE "academics_assessment"
    ADD CONSTRAINT "academics_assessment_assessment_type_id_fk"
    FOREIGN KEY ("assessment_type_id") REFERENCES "academics_assessmenttype" ("id")
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX IF NOT EXISTS "academics_assessment_assessment_type_id_idx"
    ON "academics_assessment" ("assessment_type_id");

-- -----------------------------------------------------------------------------
-- 3. Add assessment FK to students_grade
-- -----------------------------------------------------------------------------
ALTER TABLE "students_grade"
    ADD COLUMN IF NOT EXISTS "assessment_id" bigint NULL;

ALTER TABLE "students_grade"
    ADD CONSTRAINT "students_grade_assessment_id_fk"
    FOREIGN KEY ("assessment_id") REFERENCES "academics_assessment" ("id")
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX IF NOT EXISTS "students_grade_assessment_id_idx"
    ON "students_grade" ("assessment_id");

CREATE INDEX IF NOT EXISTS "students_grade_assessment_student_idx"
    ON "students_grade" ("assessment_id", "student_id");

-- -----------------------------------------------------------------------------
-- 4. Backfill: link existing grades to assessments by category/type heuristic
-- -----------------------------------------------------------------------------
-- Existing grades were created with assessment_type 'exam' or 'test'. For each
-- assessment (which knows its class/subject/session/category) we link matching
-- grades (subject + session + legacy type derived from category) so existing
-- data remains usable.
UPDATE students_grade g
SET assessment_id = sub.assessment_id
FROM (
    SELECT
        a.id AS assessment_id,
        CASE
            WHEN a.category = 'examination' THEN 'exam'
            ELSE 'test'
        END AS legacy_type,
        a.class_obj_id,
        a.subject_id,
        a.academic_session_id
    FROM academics_assessment a
) sub
WHERE g.assessment_id IS NULL
  AND g.subject_id = sub.subject_id
  AND g.academic_session_id = sub.academic_session_id
  AND g.assessment_type = sub.legacy_type
  AND g.student_id IN (
      SELECT sc.student_id
      FROM academics_studentclass sc
      WHERE sc.class_obj_id = sub.class_obj_id
        AND sc.is_active = TRUE
  );

-- -----------------------------------------------------------------------------
-- 5. Seed default assessment types (best-effort, one row per school)
-- -----------------------------------------------------------------------------
-- Only for schools that have no assessment types configured yet. Weights follow
-- a typical Ghanaian/WASSCE-style scheme and are meant to be adjusted by admins:
--   Assignment 10%, Class Exercise 5%, Quiz 15%, Exam 70%
INSERT INTO academics_assessmenttype (
    name,
    category,
    weight_percentage,
    is_active,
    created_at,
    updated_at,
    school_id,
    academic_session_id
)
SELECT
    t.name,
    t.category,
    t.weight_percentage,
    TRUE,
    NOW(),
    NOW(),
    s.id,
    NULL  -- applies to all sessions (global default)
FROM schools_school s
CROSS JOIN (
    VALUES
        ('Assignment', 'continuous_assessment', 10),
        ('Class Exercise', 'continuous_assessment', 5),
        ('Quiz', 'continuous_assessment', 15),
        ('Exam', 'examination', 70)
) AS t(name, category, weight_percentage)
WHERE NOT EXISTS (
    SELECT 1 FROM academics_assessmenttype at
    WHERE at.school_id = s.id
);

-- -----------------------------------------------------------------------------
-- 6. Backfill: set assessment_type + weight on existing assessments from defaults
-- -----------------------------------------------------------------------------
-- Match existing assessments to the seeded global type by title (case-insensitive)
-- so the type linkage and weight become visible immediately.
UPDATE academics_assessment a
SET assessment_type_id = at.id,
    weight_percentage = at.weight_percentage
FROM academics_assessmenttype at
WHERE a.assessment_type_id IS NULL
  AND a.school_id = at.school_id
  AND at.academic_session_id IS NULL
  AND LOWER(a.title) LIKE '%' || LOWER(at.name) || '%'
  AND (
      (a.category = 'examination' AND at.category = 'examination')
      OR
      (a.category = 'continuous_assessment' AND at.category = 'continuous_assessment')
  );
