# Generated by Django 4.2.7 on 2026-02-15 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '__first__'),
        ('schools', '__first__'),
        ('billing', '0002_fee_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassFeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_fee_assignments', to='academics.class')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='SchoolFeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentFeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='feetype',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='feetype',
            name='school',
        ),
        migrations.RemoveField(
            model_name='studentfee',
            name='fee_type',
        ),
        migrations.RemoveField(
            model_name='studentfee',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='fee',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='fee',
            name='status',
        ),
        migrations.AddField(
            model_name='fee',
            name='fee_type',
            field=models.CharField(choices=[('academic', 'Academic'), ('administrative', 'Administrative'), ('other', 'Other')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='is_mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_fees', to='schools.school'),
        ),
        migrations.DeleteModel(
            name='ClassFee',
        ),
        migrations.DeleteModel(
            name='FeeType',
        ),
        migrations.DeleteModel(
            name='StudentFee',
        ),
        migrations.AddField(
            model_name='studentfeeassignment',
            name='fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='billing.fee'),
        ),
        migrations.AddField(
            model_name='studentfeeassignment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolfeeassignment',
            name='fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_assignments', to='billing.fee'),
        ),
        migrations.AddField(
            model_name='schoolfeeassignment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_fee_assignments', to='schools.school'),
        ),
        migrations.AddField(
            model_name='classfeeassignment',
            name='fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='billing.fee'),
        ),
        migrations.AlterUniqueTogether(
            name='studentfeeassignment',
            unique_together={('student', 'fee')},
        ),
        migrations.AlterUniqueTogether(
            name='schoolfeeassignment',
            unique_together={('school', 'fee')},
        ),
        migrations.AlterUniqueTogether(
            name='classfeeassignment',
            unique_together={('class_obj', 'fee')},
        ),
    ]
