# Generated by Django 4.2.7 on 2026-02-24 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_add_fee_fields'),
        ('billing', '0003_classfeeassignment_schoolfeeassignment_and_more'),
    ]

    operations = [
    ]
