# Generated by Django 4.2.7 on 2026-02-03 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '__first__'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('term', models.IntegerField(choices=[(1, 'First Term'), (2, 'Second Term'), (3, 'Third Term'), (4, 'Fourth Term')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_sessions', to='schools.school')),
            ],
            options={
                'unique_together': {('school', 'name')},
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TerminalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.FloatField(default=0)),
                ('average_marks', models.FloatField(default=0)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('total_students', models.IntegerField(default=0)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('total_days', models.IntegerField(default=0)),
                ('days_present', models.IntegerField(default=0)),
                ('attendance_percentage', models.FloatField(default=0)),
                ('form_teacher_remarks', models.TextField(blank=True)),
                ('principal_remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_reports', to='academics.academicsession')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_reports', to='academics.class')),
                ('generated_by', models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'school_admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_reports', to='schools.school')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='terminal_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'class_obj', 'academic_session')},
                'ordering': ['-academic_session', 'position'],
            },
        ),
        migrations.CreateModel(
            name='SubjectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca1_score', models.FloatField(blank=True, null=True)),
                ('ca2_score', models.FloatField(blank=True, null=True)),
                ('ca3_score', models.FloatField(blank=True, null=True)),
                ('exam_score', models.FloatField(blank=True, null=True)),
                ('total_score', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('remarks', models.CharField(blank=True, max_length=100)),
                ('subject_position', models.IntegerField(blank=True, null=True)),
                ('subject_total_students', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('terminal_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_scores', to='academics.terminalreport')),
            ],
            options={
                'unique_together': {('terminal_report', 'subject')},
            },
        ),
        migrations.AddIndex(
            model_name='terminalreport',
            index=models.Index(fields=['student', 'academic_session'], name='academics_t_student_4f4b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='terminalreport',
            index=models.Index(fields=['class_obj', 'academic_session'], name='academics_t_class_ob_caa4be_idx'),
        ),
        migrations.AddIndex(
            model_name='academicsession',
            index=models.Index(fields=['school', 'is_current'], name='academics_a_school__7e4f60_idx'),
        ),
    ]

