# Generated by Django 4.2.7 on 2026-01-14 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.FloatField(default=0.0)),
                ('current_gpa', models.FloatField(default=0.0)),
                ('total_credits', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='gpa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student GPAs',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('exam', 'Exam'), ('test', 'Test'), ('quiz', 'Quiz'), ('continuous', 'Continuous Assessment'), ('assignment', 'Assignment')], max_length=20)),
                ('score', models.FloatField()),
                ('max_score', models.FloatField(default=100)),
                ('percentage', models.FloatField(editable=False)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('recorded_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
            options={
                'ordering': ['-recorded_date'],
            },
        ),
    ]
