name: Deploy Django to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.6

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd /home/ubuntu/SMS-backend-main1

            git pull origin main

            source venv/bin/activate
            pip install -r requirements.txt

            python manage.py migrate
            python manage.py collectstatic --noinput

            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
